spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-service:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/users/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback

        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/content/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: contentServiceCircuitBreaker
                fallbackUri: forward:/fallback

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: commentServiceCircuitBreaker
                fallbackUri: forward:/fallback

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: analyticsServiceCircuitBreaker
                fallbackUri: forward:/fallback

server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG